#
# _    _            _               _____ _               _
#| |  | |          | |             / ____| |             | |
#| |__| | __ _  ___| | _____ _ __ | |    | |__   ___  ___| | _____ _ __
#|  __  |/ _` |/ __| |/ / _ \ '__ | |    | '_ \ / _ \/ __| |/ / _ \ '__|
#| |  | | (_| | (__|   <  __/ |   | |____| | | |  __/ (__|   <  __/ |
#|_|  |_|\__,_|\___|_|\_\___|_|    \_____|_| |_|\___|\___|_|\_\___|_|
#
# By Damgel

Messages:
  check-usage: '&cОшибка!&r&7 Использование: &a/check [игрок]'
  contact-usage: '&cОшибка!&r&7 Использование: &a/contact [текст]'

  player-not-online: '&4Игрок не в сети'

  player-on-check: '&bИгрок вызван на проверку'
  player-is-free: '&aИгрок сводобен'
  no-one-check: '&7В данный момент вас никто не проверяет'
  message-from: 'Сообщение от'
  message-send: 'Сообщение отпровлено'

Title:
  title: '&6ПРОВЕРКА!'
  subtitle: 'Напишите /contact и свой Дискорд!'